Feature: Held Item Lore
Polyfrost/EvergreenHUD pull request #22
Opened 2023-12-11 03:23 UTC by RayDeeUx

## Description
Adds a new HUD displaying the name and lore of an item (if any).
Also has options to have HUD persist indefinitely and remove empty lines.

## How to test
Search for `Held Item Lore` in OneConfig and enable. Adjust position via `Edit HUD` and adjust other options as necessary.

## Release Notes

```release-note
Add new Held Item Lore HUD, including options to show Item Lore indefinitely and remove empty lines in the item lore.
```

2023-12-11 13:14 UTC, Wyvest requested changes

2023-12-11 13:14 UTC, Wyvest commented on src/main/java/org/polyfrost/evergreenhud/mixins/GuiIngameAccessor.java
> +public interface GuiIngameAccessor {
Remove the unused methods here

2023-12-11 13:14 UTC, Wyvest commented on src/main/kotlin/org/polyfrost/evergreenhud/hud/HeldItemLore.kt
> +        @Switch(name = "Fade Out (Instantly)", description = "If disabled, the Held Item Lore HUD will remain on the screen indefinitely.")
Remove the "(instantly)" part

2023-12-11 13:14 UTC, Wyvest commented on src/main/kotlin/org/polyfrost/evergreenhud/hud/HeldItemLore.kt
> +            "§bExample Item Lore §7(Left click and hold to drag this!)",
I love this btw

2023-12-12 02:12 UTC, MicrocontrollersDev commented on src/main/kotlin/org/polyfrost/evergreenhud/hud/HeldItemLore.kt
> +        @Switch(name = "Instant Fade", description = "Requires \"Fade Out\" to be enabled, otherwise this toggle is ignored.")
why not just `addDependency("instantFade", "fadeOut")` or whatever it is in kotlin if its different

2023-12-12 15:18 UTC, merged